### ISSUE TITLE
Error: Uncaught (in promise): TypeError: undefined is not a function

### ISSUE THREAD

**Issue by mackers** [ushahidi/tenfour-mobile#304]
https://sentry.io/ushahidi/tenfour-pwa/issues/748960677/

```
Error: Uncaught (in promise): TypeError: undefined is not a function
TypeError: undefined is not a function
    at https://app.tenfour.org/build/main.js:1:818923
    at t.invoke (https://app.tenfour.org/build/polyfills.js:3:14976)
    at Object.t._inner.t._inner.fork.onInvoke (https://app.tenfour.org/build/vendor.js:1:93694)
    at t.invoke (https://app.tenfour.org/build/polyfills.js:3:14946)
    at r.run (https://app.tenfour.org/build/polyfills.js:3:10143)
    at https://app.tenfour.org/build/polyfills.js:3:20242
    at t.invokeTask (https://app.tenfour.org/build/polyfills.js:3:15660)
    at Object.t._inner.t._inner.fork.onInvokeTask (https://app.tenfour.org/build/vendor.js:1:93608)
    at t.invokeTask (https://app.tenfour.org/build/polyfills.js:3:15619)
    at r.runTask (https://app.tenfour.org/build/polyfills.js:3:10834)
    at o (https://app.tenfour.org/build/polyfills.js:3:7894)
    at e.invokeTask [as invoke] (https://app.tenfour.org/build/polyfills.js:3:16823)
    at p (https://app.tenfour.org/build/polyfills.js:2:27648)
    at HTMLDocument.v (https://app.tenfour.org/build/polyfills.js:2:27893)
  at None (../../src/providers/firebase/firebase.ts:68:19)
  at t.invoke (/polyfills.js:3:14976)
  at t.invoke (/polyfills.js:3:14946)
  at r.run (/polyfills.js:3:10143)
  at None (/polyfills.js:3:20242)
...
(19 additional frame(s) were not displayed)
```

**Comment by dalezak** [comment]
I don't believe this has happening anymore... closing issue.
